### ISSUE TITLE
Pas de réponse automatique

### ISSUE THREAD

**Issue by M1ckael** [chtipepere/woocommerceAtosPlugin#10]
Salut,
Tout d'aborb merci pour le plugin !
J'ai installé le plugin et il est paramétré correctement. J'utilise la dernière version de Wordpress et Woocommerce.
Tout fonctionne sauf l'auto reponse, j'ai bien créé la page avec le shortcode, mais apparement elle ne receptionne pas les donnée de la banque... bizard car à la fin de mon paiement je clique sur "retour sur la boutique, je suis redirigé vers la page de reponse auto et la les mails sont envoyés et la commande est passée en "payé"

As tu une solution ou un idée?
Merci

**Comment by chtipepere** [comment]
Bonsoir,

Pourrais-tu me donner plus d'informations sur ta configuration :
- version de php
- version de wordpress
- version de woocommerce
- version du plugin

Merci,
πR
