### ISSUE TITLE
Ecran blanc

### ISSUE THREAD

**Issue by tyler19e** [chtipepere/woocommerceAtosPlugin#11]
Bonjour,

Merci beaucoup pour ce dev!
En revanche j'ai un écran blanc quand j'active le pluggin !

J'ai installé précédemment installé un pluggin équivalent de Doc type (https://github.com/doctype-fr/woocommerce-gateway-atos) mais je l'avais desintallé (suppression du pluggin dans filezilla) avant d'installer celui-ci mais rien à faire, si je remets tes fichiers, écran blanc.
Merci de me dire si tu as une piste !

A disposition pour toute question.

Clément

**Comment by chtipepere** [comment]
Bonsoir Clément,

La page blanche doit correspondre à une erreur Fatal PHP.

As-tu accès au logs php sur ta machine ?
Quelle version de PHP, wordpress et woocommerce utilises-tu ?

Merci pour tes précisions,
πR

**Comment by tyler19e** [comment]
Bonjour Pierre,

Merci pour ta réponse rapide !

https://logs.ovh.net/keial.fr/osl/keial.fr-03-09-2015.log

Je suis chez OVH Php 5.4 + wordpress et woocommerce derniere version !

Dis moi si ca te parle ou si tu as besoin d'information complémentaires

**Comment by chtipepere** [comment]
Les logs sont protégés par mot de login/passe.
Peux-tu en copier/coller une partie ici ?

πR

**Comment by tyler19e** [comment]
Voici le fichier log Error d'hier je ne sais pas si c'est ça que tu cherches?
https://www.dropbox.com/s/4rl2nmhjtq65i6p/error%20log%20keial.fr%2003%2009%202015.txt?dl=0

**Comment by tyler19e** [comment]
Et le web log https://www.dropbox.com/s/9b8wirj50tlvf60/web%20log%20keial.fr%2003%2009%202015.txt?dl=0

**Comment by chtipepere** [comment]
Bonjour,

L'error log commence à 19h, j'aurais besoin de la plage horaire de 15h à 16h (où il semblerait que tu ai rencontré les pages blanches avec l'activation du plugin).

Merci,
πR

**Comment by tyler19e** [comment]
Hier c'était plutot vers 18h l'écran blanc de mémoire. C'est l'erreur log complet d'hier que je t'ai envoyé.

Je l'ai refait la manip à 10h ce matin, toujours écran blanc quand j'active le plugin.Voici le weblog.
https://www.dropbox.com/s/wub6b8ojvlltdvl/web%20log%20keial.fr%2004%2009%202015.txt?dl=0
L'erreur log est daté de 5h du matin donc pas de nouvelles data.
... voila tout ce que je sais !

**Comment by chtipepere** [comment]
Le "weblog" correspond aux logs apache. Et ceux-ci ne sont pas suffisants pour investiguer.

Je vais essayer de en php5.4 avec les dernières versions de wordpress/woocommerce, et je mettrai à jour ce ticket.

πR

**Comment by tyler19e** [comment]
Merci beaucoup ! 
Oui désolé je pense que j'ai n'ai que ça mais je t'avoue que je ne suis pas assez calé pour aller plus loin.

Bon courage et n'hésite pas si je peux t'aider.

Clément

**Comment by chtipepere** [comment]
@tyler19e As-tu réussi à régler le souci ?
Merci,
πR

**Comment by tyler19e** [comment]
Bonjour Pierre,

Depuis j'ai pris une solution payante :(

Bon courage pour la suite !

2016-03-05 21:59 GMT+01:00 Marichez Pierre notifications@github.com:

**Comment by chtipepere** [comment]
Aucun problème, tant que tu as ce que tu souhaites ;)

πR
