### ISSUE TITLE
Warning: sprintf() [function.sprintf]

### ISSUE THREAD

**Issue by AxelRAfond** [chtipepere/woocommerceAtosPlugin#14]
Bonjour @chtipepere ,
je suis actuellement entrain de tester, sur Wamp, votre plugin Atos pour woocommerce (2.5.2). Après l'installation dans Wordpress 4.4.2, j'obtiens un message :
Warning: sprintf() [function.sprintf]: Too few arguments in C:\wamp\www\MonSite\wp-content\plugins\woocommerceatos\index.php on line 108 
Avez-vous une idée du probleme? Merci d'avance. AM

**Comment by chtipepere** [comment]
@AxelRAfond Je viens de tester avec Wordpress 4.4.2 et Woocommerce 2.5.3 et je ne rencontre aucun souci.
Quelle est votre version de php ?
Quand avez-vous rencontré ce souci ?

**Comment by chtipepere** [comment]
@AxelRAfond J'ai réussi à reproduire le souci.
Je prépare une nouvelle version du plugin.

**Comment by AxelRAfond** [comment]
Bonjour, j'ai la version 5.3.5 de PHP, le problème se situe dans l'admin (désolé je n'avais pas précisé).
Merci en tout cas de votre aide et implication. J'attends la correction avec impatience. Merci.

**Comment by chtipepere** [comment]
@AxelRAfond La version 1.2.3 vient d'être livrée avec ce correctif.
N'hésitez pas à indiquer la compatibilité du plugin ici : https://wordpress.org/plugins/woocommerceatos/
(dans la colonne de droite, en bas).
Merci pour votre retour.
