### ISSUE TITLE
Regression au passage en 1.2.3 (logo_id1)

### ISSUE THREAD

**Issue by yciabaud** [chtipepere/woocommerceAtosPlugin#15]
# Report an issue

**Indicate the context**
- [ ] PHP version 5.3.3
- [ ] Wordpress version 4.4.2
- [ ] Woocommerce version 
- [ ] Plugin version 1.2.3

**Explain your issue**
Après mise à jour, la redirection ne se fait plus à cause d'un soucis avec le logo_id1

> Erreur de l'API Atos : Invalid Keyword in parameter (logo_id1=logo_id1.gif)"

J'ai retiré le nouveau paramètre pour rétablir le service, c'est peut être limité à mercanet (mon client est à la BNP) mais je n'ai pas trouvé comment contourner le problème sans modifier le code.

**Comment by TheEidj** [comment]
Bonjour Yciabaud !
Même configuration que toi, même problème. 
J'ai essayé de comprendre d'où ça venait également sans plus de succès.
Du coup, en attendant une "vraie" solution, pourrais-tu m'indiquer quelles sont les lignes que tu as modifié pour retirer le paramètre, si possible ?
D'avance merci !

**Comment by yciabaud** [comment]
Oui c'est dans [index.php](https://github.com/chtipepere/woocommerceAtosPlugin/blob/master/index.php#L339), il faut commenter la ligne `$this->addParam( 'logo_id1', $this->logo_id1 );`

**Comment by TheEidj** [comment]
Je te remercie !

**Comment by gianniexposito06** [comment]
Bonjour j'ai le même soucis avec mon site.
Je suis sur la ligne indiqué ci dessus dans le fichier index.php de l'api woocommerce atos.
Quand vous dites "commenter" la ligne, c'est à dire ?
(Vouliez vous dire retirer la ligne ?) Merci pour votre aide précieuse...

**Comment by gianniexposito06** [comment]
Bon je l'ai "retiré" de moi même et ça refonctionne apparemment ! Bravo

**Comment by yciabaud** [comment]
Par "commenter" je voulais dire de rajouter `//` en début de ligne ou `/* ligne */` pour que la ligne ne soit plus interprétée par PHP mais laisser une trace de la modification pour ne pas l'oublier.

La retirer fonctionne donc tout autant en effet!

**Comment by gianniexposito06** [comment]
Ok merci. Moi je l'ai retirer complètement et ca semble fonctionner. Restons en contact merci

Envoyé de mon iPhone

**Comment by Jordan-Volcano** [comment]
Bonjour,

J'ai moi aussi eu le problème pour un client(sous scellius), j'ai commenter la ligne affecter. En attente d'une maj.
Pour info : 

Version WP : 		4.6.1
Version WC : 		2.6.9
Version PHP: 		5.6.25
WoocommerceAtos  1.2.3

Merci beaucoup.
