### ISSUE TITLE
"Success" don't work in the response 

### ISSUE THREAD

**Issue by FredericAssemat** [chtipepere/woocommerceAtosPlugin#2]
Hello

when the bank confirm the payment, the gateway don't receive the response "success".
And my woocommerce keep in "waiting payment" for this customer.
However, the param "response" is ok...

An idea?

Thank you

**Comment by chtipepere** [comment]
Hi,

I've checked the plugin on a fresh install, and I think I know why it's not working for you.
As said in the doc:

> Create a page that contains shortcode above and fill the automatic_response_url field in admin.
> [woocommerce_atos_automatic_response]

Which means you have to:
- create a new wordpress page
- add the snippet above in the page content
- retrieve the page url and copy it
- go to the plugin settings and paste the page url in the automatic_response field

Hope it fixes your issue.
πR

**Comment by FredericAssemat** [comment]
Hello

It works!
Excuse me for forgetting.
Thanks for all!

Fred
