### ISSUE TITLE
[woocommerce_atos_automatic_response] sans réponse.

### ISSUE THREAD

**Issue by seangoogoo** [chtipepere/woocommerceAtosPlugin#20]
# Report an issue
- [5.4.45 ] PHP version
- [4.5.3 ] Wordpress version
- [2.6.4 ] Woocommerce version
- [1.2.3 ] Plugin version

Bonjour, 
Tout le processus de paiement ce passe bien jusqu'au retour de la banque vers la page de réponse automatique qui se charge bien mais n'affiche rien. Cette page comprend pourtant bien le shortcode [woocommerce_atos_automatic_response]. Tout le dossier woocommerceatos a été chmodé en exécution. Mon fichier parcom.[monIDcommercant] comprend bien les bons chemins. Je ne comprend pas. Pouvez-vous m'aider ?

**Comment by u451f** [comment]
même souci que #18
