### ISSUE TITLE
Url de la réponse automatique

### ISSUE THREAD

**Issue by MathieuDuboy** [chtipepere/woocommerceAtosPlugin#3]
Bonjour , je recontre un petit soucis concernant la réponse automatique de avec mon plugin Atos woocommerce.

J'ai crée une page auto_reponse contenant le shortcode mais celle ci n'est pas appelée lors de la confirmation de paiement code 00.
Si je renseigne le meme URL dans l'onglet : Url de retour normale et que je clique sur "retour boutique" lors du paiement, ma page s'affiche correctement et le paiement passe en statut "completed",etc.

D'ou peut venir ce problème ? Merci d'avance

**Comment by MathieuDuboy** [comment]
Je complete mon explication : 
Ma page réponse automatique crée sous Wordpress possède l'url http://www.sitepipo.com/reponse_auto/

J'ai donc renseigné cet URL dans le champ prévu à cet effet.
Il semblerait que le plugin ne fasse pas appel à cette page en réponse automatique car le statut de la vente est inchangé.
Or comme dis plus haut, si je mets cet URL dans l'onglet "URL de retour normale" et que je clique sur "Retour Boutique" lors du succès paiement, tous les paramètres Woocommerce sont mis à jour : Order, statut, ...

Pourquoi l'appel à http://www.sitepipo.com/reponse_auto/ ne se fait pas automatiquement s'il vous plait ? 
Vous me seriez d'une grande aide car je ne comprends pas d'où le problème peut bien venir.
Merci d'avance

Mathieu

**Comment by FredericAssemat** [comment]
Hello, même soucis...
Si je "paye" par la CB sur le site sécurisé de la banque, je ne quitte pas cette page.
Si j'en sors sans cliquer sur "retour boutique", mon site n'est pas au courant que la personne a payé.
Très dangereux...
Que fait on de mal?
Merci

**Comment by MathieuDuboy** [comment]
Bonsoir, mon problème fut tout simple comme souvent ! Une journée de perdue à chercher l'erreur devant mon nez.

Ce qui bloquait mon plugin de fonctionner correctement était l'utilisation d'un .htaccess couplé avec l'utilisation d'un .htpaswd.
Je souhaitais bloquer l'accès aux internautes à la racine du site et au final cela bloquait complètement le plugin.

En espérant vous avoir aidé

**Comment by chtipepere** [comment]
Content de voir que vous avez trouvé la solution.
Ne parvenant pas à reproduire le souci de mon côté, il m'était difficile de vous apportez une réponse.
@FredericAssemat avez-vous le même souci ? En faisant des tests de mon côté, je vois bien l'appel automatique de la banque dans les logs apache (sans quitter l'interface de la banque).

**Comment by FredericAssemat** [comment]
Hello,

en fait, il ne se passe rien : 
- je passe sur la page de la banque 
- je rentre une carte bancaire ok
- je passe sur la page "Votre transaction a bien été enregistrée " avec un bouton "retour à la boutique"
- si je ne fais rien, je reste sur cette page => pas de retour automatique vers la boutique et surtout, le statut du paiement reste à "en attente" du côté backoffice woocommerce => je ne reçois aucune confirmation que le paiement est ok
- si je sors directement => ce statut reste à "en attente", donc pas bon
- si je clique sur "retour à la boutique", le statut passe à "terminé"

Donc voilà mon soucis : y'a pas d'envoi automatique suite au paiement. SI pas d'actions réelles de cliquer sur le bouton, je ne suis pas au courant du paiement.

Pour le paramétrage : 
- J'ai choisi de faire mon retour automatique vers la page "success", paramétré dans le plugin woocommerceAtos
- j'ai donc ajouté le shortcode en début de cette page, et derrière, j'ai ajouté des phrases simples en html indiquant que la personne va recevoir un mail, etc...

Où ai-je foiré?

En vous remerciant,

Fred

**Comment by FredericAssemat** [comment]
J'ai enfin trouvé...
En fait, comme je suis en mode "test", j'ai mis un plugin "members" sur le site wordpress, afin qu'il ne soit pas accessible.
Evidemment, en test, je suis en mode admin, mais depuis son https, la banque qui fait l'appel elle-même n'arrive pas à passer son "success". Si je clique sur "retour boutique", je repasse le "success" avec mon compte admin qui fonctionne.
Du coup, c'est bon : j'ai désactivé le "members" et ça passe!
Vraiment désolé de ne pas avoir pensé à cela, qui rejoint un peu le soucis du htaccess : peut-être en parler dans votre doc, histoire qu'on soit pas 12 à vous faire la même erreur ;)

**Comment by chtipepere** [comment]
Doc updated.
https://github.com/chtipepere/woocommerceAtosPlugin/commit/a7c383dd4b98788d4e5153483736ee9124cf9677

**Comment by uknowcreation** [comment]
Bonjour à tous j'ai le soucis justement  avec atos spis sous woocommerce mon paiement est bien effectué, quand je retorune sur la boutiqeue via url de retour paiement success, mon panier n'est pas vider est mon produit reste en attente de paiement dans le back office.
Personnellement la je rsete bloqué à savoir que j'ai

Paramètres commande

Les paramètres sont ajoutés à vos URLs de pages pour traiter des actions spécifiques pendant le processus de commande. Ils doivent être unique.

Payer  
order-pay
Commande reçue  
order-received
Ajouter méthode de paiement  
add-payment-method

et donc mes urls je ne vois pas comment les transmettre dans le atos spis

**Comment by chtipepere** [comment]
@uknowcreation J'ai du mal à vous lire, et donc à vous comprendre.
Vous pouvez vous exprimer en anglais si vous le préférez.
