### ISSUE TITLE
Logos sur page de la banque

### ISSUE THREAD

**Issue by FredericAssemat** [chtipepere/woocommerceAtosPlugin#4]
Bonjour,

j'ai bien envoyé chez Atos mes 3 logos que je veux voir sur leur page de paiement.
J'ai bien renseigné pour "logo id2" et "advert" dans la page de paramétrage du plugin (où est le logo id1 d'ailleurs?), mais cela ne fonctionne pas, alors qu'ils me disent bien les avoir installer et donc attendre l'appel pour les afficher.

Merci par avance

Fred

**Comment by FredericAssemat** [comment]
Par contre, j'ai toujours ce soucis...
La banque me répond sans cesse que tout est bon de leur côté, et impossible d'avoir nos logos sur leur page, alors que je fais bien l'appel me semble t'il :/

**Comment by FredericAssemat** [comment]
Hello

avez-vous pu identifier le problème?
En vous remerciant,

Fred

**Comment by chtipepere** [comment]
Bonsoir,

Pourriez-vous me copier/coller un exemple de valeur que vous avez saisi dans un des champs image ?

Merci.

**Comment by FredericAssemat** [comment]
Bonjour,

d'après les docs de paramétrage de la banque, et leurs retours mails, on doit simplement "appeler" les fichiers image avec leurs noms tels qu'envoyés.
J'ai pas fait bien compliqué : pour la valeur "Logo id2", il y a : logo2_id2.gif; et pour Advert, il y a : "advert.gif"
Merci par avance

Fred

**Comment by chtipepere** [comment]
Bonsoir,

Avez-vous précisé le bon répertoire source dans le fichier pathfile pour la variable :
`D_LOGO!/wp-content/plugins/woocommerceAtosPlugin/images/!`

Aussi, le logo_id1 a été [rajouté](https://github.com/chtipepere/woocommerceAtosPlugin/commit/543ede4f16b9fe71d406fc12c57b76107c6a3b9c).

πR

**Comment by chtipepere** [comment]
En fonction de votre réponse, je créerai une nouvelle release (ou non).

**Comment by FredericAssemat** [comment]
Bonjour,

La variable D_LOGO! est bien précisée dans le pathfile, même s'il ne s'agit pas de celle-ci : j'ai mis celui que m'avait envoyé la banque SG, avec tous les logos bancaires, (VISA, mastercard,etc...) qui s'affichent bien à l'écran. Par contre, à l'intérieur de ce répetoire, je n'ai jamais mis les logos que je veux voir affiché sur la page de paiement Atos, puisque ceux-ci sont fournis en appel par la banque, si je comprends bien leur doc.
Je les ai toutefois déposés dans le répertoire, au cas où, mais sans résultat...

A noter que j'ai implémenté index.php pour ajouter le logo_id1 comme fait dans votre modif, mais cela n'a pas marché : au moment de l'appel à la page de paiement, cela plante...

Merci pour votre aide!

**Comment by FredericAssemat** [comment]
Hello,

je viens de sortir du mode test et de faire de la préprod avec la banque : les logos apparaissent!
Visiblement, il est impossible de faire du test pour les logos : on ne peut que constater leur arrivée qu'une fois passé avec tout le paramétrage de Prod.
En m'excusant de ne pas y avoir pensé plus tôt, mais la banque m'assurait que cela devait pourtant fonctionner!
Du coup, pour moi, tout est maintenant OK!!!
Merci pour ce plugin et votre dispo, il est au top :)

**Comment by chtipepere** [comment]
Je peux fermer cette issue du coup ?
Manque-t-il de la clarté dans la documentation ?

**Comment by FredericAssemat** [comment]
Je pense que vous pouvez fermer, mais ce serait en effet pas mal cool de dire dans la doc que, pour les logos, cela ne marche qu'une fois le merchant-id activé auprès de la banque, avec des tests directement sur une plateforme de préprod.
