### ISSUE TITLE
Mauvais retour E-commerce en cas de succès de paiement

### ISSUE THREAD

**Issue by FredericAssemat** [chtipepere/woocommerceAtosPlugin#5]
Hello,

Suite à nombreux test, je m'aperçois que, suite au paiement ok et retour de la banque, le retour woocommerce passe à "completed order" - qui signifie que la commande est totalement terminée, y compris l'envoi du produit - au lieu de "processing order", qui signifie bien pour woocommerce que le paiement a fonctionné, mais qu'il reste encore à effectuer l'envoi.

Avez-vous le même comportement? 
Pouvez-vous corriger?

En vous remerciant,

Frédéric Assémat

**Comment by chtipepere** [comment]
Fixed.
https://github.com/chtipepere/woocommerceAtosPlugin/commit/833438441bd51a3fa24aecbd40555b7c830d5d77
