### ISSUE TITLE
Fatal error with the last version

### ISSUE THREAD

**Issue by azralth** [chtipepere/woocommerceAtosPlugin#6]
Hello,

i try to install the last version of your plugin but get this erro when i activate it : 

Fatal error: Access level to Woocommerce_atos::$form_fields must be public (as in class WC_Payment_Gateway) in /home/frenchdewx/www/wp-content/plugins/woocommerceatos/index.php on line 101

Can you hel me ?

**Comment by FredericAssemat** [comment]
Je confirme...
La mise à jour du plugin a créé une page blanche du site entier.
Plugin désactivé, retour sur l'ancien binaire et juste modification de la ligne corrigé (completed / processing) , et ça roule.

Il y a donc un soucis avec la mise à jour auto du plugin wordpress.

**Comment by chtipepere** [comment]
Change the form_fields property visibility to public (as in [parent](https://github.com/woothemes/woocommerce/blob/59d3fb5224ddfbc11c18daf9c2fdf47e82e143f1/includes/abstracts/abstract-wc-settings-api.php)).
