### ISSUE TITLE
page blanche dès que le plugin est activé

### ISSUE THREAD

**Issue by hosseinkarimi** [chtipepere/woocommerceAtosPlugin#7]
Bonjour,

Comme indiqué dans le titre, j'ai un soucis avec le plugin. Dès qu'il est activé, toutes les pages sauf la homepage et le backoffice restent blanches.

WP 4.2.2
WC 2.3.8

avez vous une idée?
Merci.

**Comment by chtipepere** [comment]
Bonjour,  
Quelle version du plugin "woocommerceAtosPlugin" utilsiez-vous ?

Si vous utilisez une version < 1.2.1, veuillez mettre à jour le plugin ([ce problème a déjà été remonté et corrigé](https://github.com/chtipepere/woocommerceAtosPlugin/issues/6)).

Merci

**Comment by hosseinkarimi** [comment]
Bonjour, oui merci. Cela était du à un autre plugin. Merci pour votre réponse.
