### ISSUE TITLE
woo commerce Atos plugin 1.2.2

### ISSUE THREAD

**Issue by MS33** [chtipepere/woocommerceAtosPlugin#8]
J'ai installé le module sur un site qui est en anglais et français. L'anglais est la langue prioritaire pour ce site (traductions gérées par WPML).

Sur la version anglaise, quand je valide le paiement d'une commande, tout fonctionne parfaitement. Voici l'URL pour le paiement ATOS:
http://MYSITE.fr/checkout/order-pay/1302/?key=wc_order_5583a6bc7b302

Sur la version française, quand je procède au paiement de ma commande, j'ai une erreur:
Désolé, cette commande est invalide et ne peut être finalisée.

Voici l'URL générée: 
http://MYSITE.fr/validation/order-pay/1302key=wc_order_5583a6bc7b302/?lang=fr

Si je traduis le checkout “Order-pay” par “commande-paiement” , voici l'URL générée:
http://MYSITE.fr/validation/commande-paiement/1302key=wc_order_5583a6bc7b302?lang=fr
et la page affiche une erreur 404.

Il semble que l'URL générée à la validation du panier commandé ne soit pas créée correctement pour le second language.

Merci pour votre réponse,

**Comment by chtipepere** [comment]
Bonsoir,

Pouvez-vous essayer avec une nouvelle commande en commençant par la version française ?

Merci de m'indiquer aussi la version de WooCommerce que vous utilisez.

πR

**Comment by MS33** [comment]
Bonjour,
le résultat est effectivement le même pour une commande en français.
la version woo commerce est 2.3.11.
Merci pour votre retour !

**Comment by chtipepere** [comment]
Je pense que le souci provient du fait qu'on ne puisse pas valider 2 fois la même commande.
De plus, à aucun moment dans le plugin woocommerceAtosPlugin n'est spécifié ce genre d'URL.

Pouvez-vous me confirmer que le paiement d'une commande est fonctionnel, en essayant une culture à la fois ?
